### ISSUE TITLE
Crash (requires old scipy version?)

### ISSUE THREAD

**Issue by texttheater** [L3viathan/compound-splitter#1]
ke@nbb-003:~/git$ cd compound-splitter/
    direnv: loading ~/git/compound-splitter/.envrc
    direnv: export +VIRTUAL_ENV ~PATH
    ke@nbb-003:~/git/compound-splitter$ pip3 install -r requirements.txt
    Processing /home/ke/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c/docopt-0.6.2-py2.py3-none-any.whl
    Processing /home/ke/.cache/pip/wheels/75/66/14/d9ff03c2c04dc7933ee5dac59a04d991c99ee2e2817744f060/gensim-0.13.4-cp38-cp38-linux_x86_64.whl
    Collecting scipy>=0.7.0
      Using cached scipy-1.5.2-cp38-cp38-manylinux1_x86_64.whl (25.7 MB)
    Collecting numpy>=1.3
      Using cached numpy-1.19.1-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
    Collecting six>=1.5.0
      Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
    Processing /home/ke/.cache/pip/wheels/a8/39/18/46aeab9eaf5317ec7f21924f2d0b11a856ad28207e87060140/smart_open-2.1.0-py3-none-any.whl
    Collecting boto
      Using cached boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
    Collecting requests
      Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
    Collecting boto3
      Using cached boto3-1.14.37-py2.py3-none-any.whl (129 kB)
    Collecting chardet<4,>=3.0.2
      Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
    Collecting certifi>=2017.4.17
      Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
    Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
      Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
    Collecting idna<3,>=2.5
      Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
    Collecting s3transfer<0.4.0,>=0.3.0
      Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
    Collecting botocore<1.18.0,>=1.17.37
      Using cached botocore-1.17.37-py2.py3-none-any.whl (6.5 MB)
    Collecting jmespath<1.0.0,>=0.7.1
      Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
    Collecting docutils<0.16,>=0.10
      Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
    Collecting python-dateutil<3.0.0,>=2.1
      Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
    Installing collected packages: docopt, numpy, scipy, six, boto, chardet, certifi, urllib3, idna, requests, docutils, python-dateutil, jmespath, botocore, s3transfer, boto3, smart-open, gensim
    Successfully installed boto-2.49.0 boto3-1.14.37 botocore-1.17.37 certifi-2020.6.20 chardet-3.0.4 docopt-0.6.2 docutils-0.15.2 gensim-0.13.4 idna-2.10 jmespath-0.10.0 numpy-1.19.1 python-dateutil-2.8.1 requests-2.24.0 s3transfer-0.3.3 scipy-1.5.2 six-1.15.0 smart-open-2.1.0 urllib3-1.25.10
    ke@nbb-003:~/git/compound-splitter$ python3 splitter.py -
    Traceback (most recent call last):
      File "/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/gensim/models/ldamodel.py", line 51, in <module>
        from scipy.maxentropy import logsumexp
    ModuleNotFoundError: No module named 'scipy.maxentropy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "splitter.py", line 484, in <module>
        spl = Splitter(language=args['--lang'], verbose=args['--verbose'], args=args)
      File "splitter.py", line 117, in __init__
        self.read_vectors()
      File "splitter.py", line 178, in read_vectors
        self.vec = pickle.load(f)
      File "/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/gensim/__init__.py", line 6, in <module>
        from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
      File "/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/gensim/models/__init__.py", line 7, in <module>
        from .coherencemodel import CoherenceModel
      File "/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/gensim/models/coherencemodel.py", line 29, in <module>
        from gensim.models.ldamodel import LdaModel
      File "/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/gensim/models/ldamodel.py", line 54, in <module>
        from scipy.misc import logsumexp
    ImportError: cannot import name 'logsumexp' from 'scipy.misc' (/home/ke/git/compound-splitter/.direnv/python-3.8.2/lib/python3.8/site-packages/scipy/misc/__init__.py)

**Comment by L3viathan** [comment]
Can confirm. The pickled models were created with a specific scipy version, which was not pinned. It should work with the new requirements.txt now.
